# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  install_dependencies:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13.9"
          cache: "pip"
      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile DAG
        run: |
          python -m compileall dags/

      - name: Pytest
        run: |
          source venv/bin/activate
          pytest tests/test_hello_world_dag.py

  DAG_build_and_test:
    runs-on: self-hosted
    permissions:
      id-token: write # needed for OIDC
      contents: read
    name: Build and Upload DAG to GCP

    needs: install_dependencies

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/1048351869749/locations/global/workloadIdentityPools/github-poolv1/providers/github-actions-v1"
          service_account: "github-action@famous-gecko-476708-q1.iam.gserviceaccount.com"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Verify identity
        run: |
          gcloud auth list
          gcloud sts tokens exchange --help >/dev/null 2>&1 || true

      - name: Deploy DAGs
        run: gsutil -m cp -r dags/ gs://us-central1-datapoc-ff10a15e-bucket

  build_and_deploy_sql_code:
    runs-on: self-hosted
    permissions:
      id-token: write # needed for OIDC
      contents: read

    name: Build and Deploy SQL code

    needs: DAG_build_and_test

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/1048351869749/locations/global/workloadIdentityPools/github-poolv1/providers/github-actions-v1"
          service_account: "github-action@famous-gecko-476708-q1.iam.gserviceaccount.com"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Download Cloud SQL Proxy
        run: |
          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          chmod +x cloud_sql_proxy
      
      - name: Wait for Cloud SQL Proxy to Start
        run: |
          ./wait-for-it.sh famous-gecko-476708-q1:us-central1:datasqlpoc:5432 -s -t 10 -- echo "Cloud SQL Proxy is running"